-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Banner"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    banner_name text COLLATE pg_catalog."default" NOT NULL,
    banner_image text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "deletedAt" timestamp(3) without time zone,
    CONSTRAINT "Banner_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Service"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    service_code text COLLATE pg_catalog."default" NOT NULL,
    service_name text COLLATE pg_catalog."default" NOT NULL,
    service_icon text COLLATE pg_catalog."default" NOT NULL,
    service_tarif double precision NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "deletedAt" timestamp(3) without time zone,
    CONSTRAINT "Service_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Transaction"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "userId" text COLLATE pg_catalog."default" NOT NULL,
    "serviceId" text COLLATE pg_catalog."default",
    "invoiceNumber" text COLLATE pg_catalog."default" NOT NULL,
    type "TransactionType" NOT NULL,
    description text COLLATE pg_catalog."default",
    amount double precision NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" timestamp(3) without time zone,
    CONSTRAINT "Transaction_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    "firstName" text COLLATE pg_catalog."default",
    "lastName" text COLLATE pg_catalog."default",
    "profileImage" text COLLATE pg_catalog."default",
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "deletedAt" timestamp(3) without time zone,
    balance double precision NOT NULL DEFAULT 0.00,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Transaction"
    ADD CONSTRAINT "Transaction_serviceId_fkey" FOREIGN KEY ("serviceId")
    REFERENCES public."Service" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Transaction"
    ADD CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "Transaction_userId_idx"
    ON public."Transaction"("userId");

END;